apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: splex7/pyapp:26
        ports:
        - containerPort: 5000
